[programs.localnet]
nft_staker = "Gfpip7T6hdF2BZZNXA5xQNrwGLPd9KCa2GgnJRZB1woE"

[programs.devnet]
nft_staker = "Gfpip7T6hdF2BZZNXA5xQNrwGLPd9KCa2GgnJRZB1woE"

[programs.mainnet]
nft_staker = "Gfpip7T6hdF2BZZNXA5xQNrwGLPd9KCa2GgnJRZB1woE"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "mainnet"
wallet = "./lib/6r7aWsBVkS78CerWgYTQweCniigZwWwRuqGr4zivr6nJ.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
